model_list:
  - model_name: openai/mimo-v2.5-free
    litellm_params:
      model: openai/mimo-v2.5-free
      api_key: os.environ/OPENCODE_API_KEY
      api_base: https://opencode.ai/zen/v1
  - model_name: openai/deepseek-v4-flash-free
    litellm_params:
      model: openai/deepseek-v4-flash-free
      api_key: os.environ/OPENCODE_API_KEY
      api_base: https://opencode.ai/zen/v1
  - model_name: openai/ling-3.0-flash-free
    litellm_params:
      model: openai/ling-3.0-flash-free
      api_key: os.environ/OPENCODE_API_KEY
      api_base: https://opencode.ai/zen/v1
  - model_name: nvidia/nemotron-3-super-120b-a12b
    litellm_params:
      model: openai/nvidia/nemotron-3-super-120b-a12b
      api_key: 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
      api_base: https://integrate.api.nvidia.com/v1
  - model_name: nvidia/nemotron-3-nano-30b-a3b
    litellm_params:
      model: openai/nvidia/nemotron-3-nano-30b-a3b
      api_key: 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
      api_base: https://integrate.api.nvidia.com/v1

litellm_settings:
  drop_params: true
  fallbacks:
    - openai/mimo-v2.5-free:
        - openai/deepseek-v4-flash-free
        - openai/ling-3.0-flash-free
        - nvidia/nemotron-3-nano-30b-a3b

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
