model_list:
  - model_name: openai/mimo-v2.5-free
    litellm_params:
      model: openai/mimo-v2.5-free
      api_key: os.environ/OPENCODE_API_KEY
      api_base: https://opencode.ai/zen/v1
  - model_name: openai/gpt-5.4-mini
    litellm_params:
      model: openai/gpt-5.4-mini
      api_key: os.environ/OPENCODE_API_KEY
      api_base: https://opencode.ai/zen/v1
  - model_name: openai/gpt-5-nano
    litellm_params:
      model: openai/gpt-5-nano
      api_key: os.environ/OPENCODE_API_KEY
      api_base: https://opencode.ai/zen/v1
  - model_name: openai/deepseek-v4-flash-free
    litellm_params:
      model: openai/deepseek-v4-flash-free
      api_key: os.environ/OPENCODE_API_KEY
      api_base: https://opencode.ai/zen/v1

litellm_settings:
  drop_params: true

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
